# Generated by Django 5.2.3 on 2025-06-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_calling', '0002_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the hospital.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='speciality',
            field=models.TextField(blank=True, help_text='e.g., Cardiology, Oncology, Pediatrics. Separate multiple specialities with commas.', null=True),
        ),
    ]
