# Generated by Django 5.2.3 on 2025-06-28 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_calling', '0003_hospital_phone_number_hospital_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_manager',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.TextField(blank=True, help_text='Full building address'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('office', 'Office'), ('ward', 'Ward'), ('lab', 'Laboratory'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description'),
        ),
        migrations.AddField(
            model_name='building',
            name='floors',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='e.g., 5', verbose_name='Number of Floors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='building',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='nurse_calling.hospital'),
        ),
    ]
