# Generated by Django 5.2.3 on 2025-06-28 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_calling', '0004_remove_building_building_manager_building_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='floor_manager',
        ),
        migrations.AddField(
            model_name='floor',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_floors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('clinical', 'Clinical'), ('research', 'Research'), ('lab', 'Labratory'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
