# Generated by Django 5.2.3 on 2025-06-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_calling', '0005_remove_floor_floor_manager_floor_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nurse_calling.building'),
            preserve_default=False,
        ),
    ]
