# Generated by Django 5.2.3 on 2025-06-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_calling', '0006_ward_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='nurses',
        ),
    ]
