# Generated by Django 5.2.3 on 2025-06-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_calling', '0007_remove_bed_nurses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
