# Generated by Django 5.2.3 on 2025-07-02 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_calling', '0008_bed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='nurse_calling.device'),
        ),
        migrations.AddField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='nurse_calling.nurse'),
        ),
    ]
